### ISSUE TITLE
您好，请教下可否把这个工具使用的具体流程写成带图的教程呢？

### ISSUE THREAD

**Issue by YDTRINLEY** [Frederick-S/yuque-to-markdown#11]
很抱歉 我最近也需要把几百篇语雀文档导出来md格式，手动操作太惨了……
找到您的分享，可是我没什么代码基础…… 只会简单的git命令
想请教大佬可否把这个工具使用的具体流程写成带图的教程呢？万分感谢

**Comment by Frederick-S** [comment]
@YDTRINLEY 感谢关注，抱歉目前项目还未完成，暂时重心在其他方向，完成后会提供教程
