### ISSUE TITLE
May I ask how to use this tool?

### ISSUE THREAD

**Issue by cool-ic** [Frederick-S/yuque-to-markdown#8]
Thanks for your great work!
May I ask how to use this tool? I have little experience on these language.

**Comment by Frederick-S** [comment]
@cool-ic It's still under development and no available docs now. It will be a web app when it's finished, so you can login with your yuque account and select a repo, then export the docs of that repo.

Here is a simple quick start guide if you are still interested in it:
1. the whole project is a standard spring boot project
2. the web folder contains the front end code which is not ready now, you can skip this part
3. follow the instructions [here](https://www.yuque.com/yuque/developer/create-oauth-apps) to create your own oauth app of yuque
4. create 3 environment variables
    1. YUQUE_CLIENT_ID: the client id created in step 3
    2. YUQUE_CLIENT_SECRET: the client secret created in step 3
    3. YUQUE_REDIRECT_URI: this should be `http://localhost:8080/oauth2/authorized` for local dev
5. launch the spring boot app
6. visit `http://localhost:8080/oauth2/authorize` to get authorized
7. explore the apis under `controller/api` folder
